---
# CADET Root Assurance Configuration
version: "1.0.0"
schema_version: "cadet-v1"
timestamp: "2025-01-14T12:00:00Z"

# Root assurance ledger configuration
cadet:
  id: "CADET-ROOT-Q100-CONF0000"
  description: "Circular Assurance by Digital Evolutive Twin - Root Registry"
  blockchain_type: "hierarchical"
  consensus_mechanism: "proof_of_evidence"
  
# Cryptographic configuration
crypto:
  hash_algorithm: "SHA-256"
  signature_algorithm: "Ed25519"
  merkle_tree: true
  immutable_ledger: true

# Domain registry (15 domains × 7 CAX = 105 nodes)
domains:
  AAA:
    name: "ARCHITECTURES_AIRFRAMES_AERODYNAMICS"
    description: "Airframe structures, aerodynamic surfaces, and architectural systems"
    owner_domain: "AAA"
    co_domains: ["MMM", "EEE", "OOO"]
    
  AAP:
    name: "AIRPORTS_ADAPTATIONS"
    description: "Airport infrastructure interfaces and ground operation adaptations"
    owner_domain: "AAP"
    co_domains: ["IIF", "LIB", "EDI"]
    
  CCC:
    name: "COCKPIT_CABIN_CARGO_SYSTEMS"
    description: "Cockpit controls, cabin systems, and cargo handling"
    owner_domain: "CCC"
    co_domains: ["EDI", "IIS", "AAA"]
    
  CQH:
    name: "CRYOGENICS_QUANTUM_INTERFACES_HYDROGEN_CELLS"
    description: "Cryogenic systems, quantum interfaces, and hydrogen fuel cells"
    owner_domain: "CQH"
    co_domains: ["PPP", "EER", "DDD"]
    
  DDD:
    name: "DEFENCE_CYBERSECURITY_SAFETY"
    description: "Defense systems, cybersecurity protocols, and safety assurance"
    owner_domain: "DDD"
    co_domains: ["EDI", "IIS", "OOO"]
    
  EDI:
    name: "ELECTRONICS_DIGITAL_INSTRUMENTS"
    description: "Electronic systems and digital instrumentation"
    owner_domain: "EDI"
    co_domains: ["LCC", "IIS", "OOO"]
    
  EEE:
    name: "ENVIRONMENTAL_REMEDIATION_CIRCULARITY"
    description: "Environmental systems and circular economy implementation"
    owner_domain: "EEE"
    co_domains: ["EER", "LIB", "AAA"]
    
  EER:
    name: "ENERGY_AND_RENEWABLE"
    description: "Energy systems and renewable power generation"
    owner_domain: "EER"
    co_domains: ["PPP", "CQH", "EDI"]
    
  IIF:
    name: "INFRASTRUCTURES_AND_FACILITIES_VALUE_CHAINS"
    description: "Infrastructure systems and value chain management"
    owner_domain: "IIF"
    co_domains: ["LIB", "AAP", "MMM"]
    
  IIS:
    name: "INTELLIGENT_SYSTEMS_ONBOARD_AI"
    description: "Intelligent systems and onboard artificial intelligence"
    owner_domain: "IIS"
    co_domains: ["EDI", "OOO", "LCC"]
    
  LCC:
    name: "LINKS_COMMUNICATIONS_CONTROL_IoT"
    description: "Communication links, control systems, and IoT integration"
    owner_domain: "LCC"
    co_domains: ["EDI", "IIS", "OOO"]
    
  LIB:
    name: "LOGISTICS_INTEGRATED_BLOCKCHAIN"
    description: "Logistics management and integrated blockchain systems"
    owner_domain: "LIB"
    co_domains: ["IIF", "EEE", "AAP"]
    
  MMM:
    name: "MECHANICAL_MATERIAL_MONITORING"
    description: "Mechanical systems, materials engineering, and monitoring"
    owner_domain: "MMM"
    co_domains: ["AAA", "IIF", "PPP"]
    
  OOO:
    name: "OPERATING_SYSTEMS_NAVIGATION_HPC"
    description: "Operating systems, navigation, and high-performance computing"
    owner_domain: "OOO"
    co_domains: ["IIS", "EDI", "LCC"]
    
  PPP:
    name: "PROPULSION_AND_FUEL"
    description: "Propulsion systems and fuel management"
    owner_domain: "PPP"
    co_domains: ["CQH", "EER", "MMM"]

# CAX pillars deployed in each domain
cax_pillars:
  CAD:
    name: "Computer-Aided Design"
    description: "Design systems and modeling"
    
  CAE:
    name: "Computer-Aided Engineering"
    description: "Engineering analysis and simulation"
    
  CAM:
    name: "Computer-Aided Manufacturing"
    description: "Manufacturing processes and production"
    
  CAT:
    name: "Computer-Aided Testing"
    description: "Testing frameworks and tools"
    
  CAI:
    name: "Computer-Aided Integration"
    description: "System integration and interfaces"
    
  CAS:
    name: "Computer-Aided Sustainment"
    description: "Sustainment and maintenance operations"
    
  CAO:
    name: "Computer-Aided Organization"
    description: "Organizational operations and ORGOPS"

# Traceability framework
traces:
  enabled: true
  bidirectional: true
  cross_domain_refs: true
  ata_sns_mapping: true
  
# Evidence requirements
evidence:
  mandatory_fields:
    - "det_id"
    - "ts"
    - "refs.ce"
    - "refs.ci" 
    - "inputs"
    - "processing.tool"
    - "processing.params"
    - "outputs.units"
    - "hash"
    - "sig"
  
  naming_pattern: "DET:<CAX>:<DOMAIN>:<SNS>:<activity>:<version>"
  versioning: "evolutionary"
  immutable: true

# Circular assurance KPIs
circularity_kpis:
  reuse_percentage: 
    target: 35
    unit: "%"
    
  co2_savings:
    target: 1000
    unit: "kg"
    
  energy_savings: 
    target: 500
    unit: "kWh"
    
  lifecycle_extension:
    target: 12
    unit: "months"

# Metadata
meta:
  owner: "CADET-Registry-Admin"
  reviewer: "Chief-Architect" 
  last_updated: "2025-01-14T12:00:00Z"
  change_ref: "INIT-CADET-REGISTRY-V1"